### ISSUE TITLE
Gettting ERROR: Cannot load message class for [detectron2_ros/Result]. Are your messages built?

### ISSUE THREAD

**Issue by sisaha9** [DavidFernandezChaves/detectron2_ros#3]
I am not sure why it keeps giving this error message. I did run catkin_make and I am able to run it and view the segmentation results in Rviz with visualizations. But I can't get the segmentation information out for some reason. Am I supposed to be changing something else in the CMakes/package.xml?

**Comment by DavidFernandezChaves** [comment]
It seems that for some reason ROS does not find the message type "Detectron2/result". Does the catking_make give error?
You should not change anything in the package.xml file.

**Comment by sisaha9** [comment]
I realized the issue. I hadn't sourced my setup.bash (didn't think it was needed if I had sourced once and the message was being generated by the node). Thanks for the prompt reply though!

**Comment by VbsmRobotic** [comment]
Hi,
I have sourced the detectron2 environment and also sourced the catkin workspace, but I face the same issue in rqt (topic: /detectron2_ros/result       can not get message class for type "detectron2_ros/Result"). I have already checked Cmakelist the custom msg already has been added there. Is there any advice about this error?
