### ISSUE TITLE
Can't catkin_make

### ISSUE THREAD

**Issue by MBaranPeker** [DavidFernandezChaves/detectron2_ros#5]
Hi @DavidFernandezChaves, 
Thank you for this great work, While installation i have not face with any problem untill compile. In chapter 4 I kind of confused. I attached 2 image in one of them I was trying to catkin_make inside the workspace in another one outside of workspace. But they both cannot source to ROS. Btw before starting the installation I already sourced to ROS with this "source /opt/ros/melodic/setup.bash" .

I will be happy if you could help me with this one.
Thanks,

![Screenshot from 2021-03-05 15-57-21](https://user-images.githubusercontent.com/9626668/110085070-9f565380-7dcb-11eb-86ae-8105cd93daaa.png)
![Screenshot from 2021-03-05 15-57-54](https://user-images.githubusercontent.com/9626668/110085086-a54c3480-7dcb-11eb-9bff-49562f682d49.png)

**Comment by DavidFernandezChaves** [comment]
Hello @MBaranPeker,
The problem you are having is not related to this ROS package, but to the creation of a workspace.
Check out the initialisation of a workspace according to their tutorial here:  http://wiki.ros.org/catkin/Tutorials/create_a_workspace

Thank you for your interest :)

**Comment by MBaranPeker** [comment]
thank you for your answer i will try that out
