### ISSUE TITLE
compile and use issues

### ISSUE THREAD

**Issue by xiaoyuamw** [DavidFernandezChaves/detectron2_ros#6]
Hi,@DavidFernandezChaves
Thank you for your great work! I had tried to compile and run your project in a virtual environment created by conda, and the compile process had successuly, however i don't know whether it will work or not by doing like this previously! Now when i run with the command line "roslaunch detectron2_ros detectron2_ros.launch", the output as bellows:
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
[WARN] [1616158634.220835]: Initializing
[INFO] [1616158634.227763]: [Detectron2] ~model: /home/robot_nb/catkin_mask/src/detectron2_ros/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
shutdown request: [/detectron2_ros] Reason: new node registered with same name
WARNING [03/19 20:57:14 d2.config.compat]: Config '/home/robot_nb/catkin_mask/src/detectron2_ros/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
[INFO] [1616158634.311513]: [Detectron2] ~detection_threshold: 0.5
[INFO] [1616158651.696466]: [Detectron2] ~visualization: True
[INFO] [1616158651.738531]: [Detectron2] ~input: ViMantic/ToCNN
[WARN] [1616158651.744645]: Initialized
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
It seems that something is wrong, because i can't see the result!
I hope you can tell me whether i can compile and run this project in a virtual environment created by conda? if your answer is yes, then what should i do to acquire the output result and whether the dataset needed?

Best Regards.

**Comment by DavidFernandezChaves** [comment]
Hello @xiaoyuamw, thank you for your comment.
I have never tested the project in conda, however, in the output you copied there is an error:

`shutdown request: [/detectron2_ros] Reason: new node registered with same name`

Is it possible that you are calling the node twice? Have you modified the launch? What other nodes have you launched?

I look forward to helping you, 
Regards.

**Comment by xiaoyuamw** [comment]
Hi @DavidFernandezChaves,
Thank you for your reply very much! I have solved the problem and got the outputs successfully, which indicates that your project can be compile and run in virtual environment created by conda. 
But now i have another question, whether you are plan to convert the AdelaiDet project (github address: https://github.com/aim-uofa/AdelaiDet) into ros version? I have done something, but failed!
Looking forward to you reply.

Best Regards.

**Comment by DavidFernandezChaves** [comment]
Not for now, thank you.
